kind: pipeline
name: default

steps:
  - name: build
    image: node:10
    commands:
      - npm install
      - npm run build
  - name: bake
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: registry.nestorrente.com/v2/nestorrente/vue-slides
      registry: registry.nestorrente.com/v2
      tags:
        - latest
        - 0.1.0.${CI_BUILD_NUMBER}
    when:
      branch:
        - master
        - release/*
  - name: deploy-dev
    image: rubasace/drone-helm-k8s
    environment:
      K8S_CERT_AUTHORITY_DATA:
        from_secret: K8S_CERT_AUTHORITY_DATA
      K8S_SERVER:
        from_secret: K8S_SERVER
      K8S_USER:
        from_secret: K8S_USER
      K8S_PASSWORD:
        from_secret: K8S_PASSWORD
      NAMESPACE: dev
      IMAGE_TAG: 0.1.0.${CI_BUILD_NUMBER}
    when:
      branch:
        - master
  - name: deploy-production
    image: rubasace/drone-helm-k8s
    environment:
      K8S_CERT_AUTHORITY_DATA:
        from_secret: K8S_CERT_AUTHORITY_DATA
      K8S_SERVER:
        from_secret: K8S_SERVER
      K8S_USER:
        from_secret: K8S_USER
      K8S_PASSWORD:
        from_secret: K8S_PASSWORD
      NAMESPACE: production
      IMAGE_TAG: 0.1.0.${CI_BUILD_NUMBER}
    when:
      branch:
        - master
